### PR TITLE
Update and rename README.md to kubeconfig.yaml

### PR DESCRIPTION
**Pull request by HemantSharma-Admin**

### CODE REVIEW

**Comment by HemantSharma-Admin** [comment]
Testing

**Review by HemantSharma-Admin — COMMENTED** [review]
good

**Comment by joshuaramirez114** [comment]
GREAT

**Review by joshuaramirez114 — APPROVED** [review]
great

**Review by joshuaramirez114 — APPROVED** [review]

**Comment by HemantSharma-Admin** [comment]
hello

**Review by joshR1999 — APPROVED** [review]
if this doesnt work call me papi

**Pull request merged**
